/* AUTO-GENERADO por scripts/build-flowbite-blocks.mjs — NO editar a mano. */
import dynamic from 'next/dynamic'
import type { ComponentType } from 'react'

/**
 * Mapa templateId (`<blockType>.<variant>`) -> componente Flowbite via next/dynamic.
 * 133 variantes. Code-split + SSR. Resuelto por el BlockRenderer (A4).
 */
export const flowbiteRegistry: Record<string, ComponentType<any>> = {
  'hero.default': dynamic(() => import('./blocks/hero/default')),
  'hero.visual-image-heading': dynamic(() => import('./blocks/hero/visual-image-heading')),
  'hero.search-datepicker': dynamic(() => import('./blocks/hero/search-datepicker')),
  'hero.email-signup-video': dynamic(() => import('./blocks/hero/email-signup-video')),
  'hero.illustration-email-signup': dynamic(() => import('./blocks/hero/illustration-email-signup')),
  'hero.cover-image-ctas': dynamic(() => import('./blocks/hero/cover-image-ctas')),
  'hero.screenshot-download': dynamic(() => import('./blocks/hero/screenshot-download')),
  'hero.search-bar': dynamic(() => import('./blocks/hero/search-bar')),
  'hero.video-embed-cta': dynamic(() => import('./blocks/hero/video-embed-cta')),
  'hero.signup-cta': dynamic(() => import('./blocks/hero/signup-cta')),
  'hero.app-preview-ctas': dynamic(() => import('./blocks/hero/app-preview-ctas')),
  'hero.background-cover-ctas': dynamic(() => import('./blocks/hero/background-cover-ctas')),
  'hero.crypto': dynamic(() => import('./blocks/hero/crypto')),
  'hero.background-image-cards': dynamic(() => import('./blocks/hero/background-image-cards')),
  'hero.carousel': dynamic(() => import('./blocks/hero/carousel')),
  'hero.book-cover': dynamic(() => import('./blocks/hero/book-cover')),
  'hero.blog-posts-featured': dynamic(() => import('./blocks/hero/blog-posts-featured')),
  'hero.phone-mockup-download': dynamic(() => import('./blocks/hero/phone-mockup-download')),
  'hero.storefront-default': dynamic(() => import('./blocks/hero/storefront-default')),
  'hero.storefront-background-image': dynamic(() => import('./blocks/hero/storefront-background-image')),
  'hero.storefront-full-slider': dynamic(() => import('./blocks/hero/storefront-full-slider')),
  'hero.storefront-grid-view': dynamic(() => import('./blocks/hero/storefront-grid-view')),
  'features.default': dynamic(() => import('./blocks/features/default')),
  'features.image-list': dynamic(() => import('./blocks/features/image-list')),
  'features.cta-list': dynamic(() => import('./blocks/features/cta-list')),
  'features.icons-list': dynamic(() => import('./blocks/features/icons-list')),
  'features.icon-list-cta': dynamic(() => import('./blocks/features/icon-list-cta')),
  'features.description-icon-list': dynamic(() => import('./blocks/features/description-icon-list')),
  'features.card-list': dynamic(() => import('./blocks/features/card-list')),
  'features.alternate': dynamic(() => import('./blocks/features/alternate')),
  'features.comparison': dynamic(() => import('./blocks/features/comparison')),
  'features.rounded-icons': dynamic(() => import('./blocks/features/rounded-icons')),
  'pricing.default': dynamic(() => import('./blocks/pricing/default')),
  'pricing.tabs-selector': dynamic(() => import('./blocks/pricing/tabs-selector')),
  'pricing.horizontal': dynamic(() => import('./blocks/pricing/horizontal')),
  'pricing.feature-list': dynamic(() => import('./blocks/pricing/feature-list')),
  'pricing.comparison-table': dynamic(() => import('./blocks/pricing/comparison-table')),
  'pricing.highlighted-plan': dynamic(() => import('./blocks/pricing/highlighted-plan')),
  'pricing.toggle': dynamic(() => import('./blocks/pricing/toggle')),
  'testimonials.blockquote': dynamic(() => import('./blocks/testimonials/blockquote')),
  'testimonials.carousel-slider': dynamic(() => import('./blocks/testimonials/carousel-slider')),
  'testimonials.grid-layout-cards': dynamic(() => import('./blocks/testimonials/grid-layout-cards')),
  'testimonials.cards': dynamic(() => import('./blocks/testimonials/cards')),
  'testimonials.tabs': dynamic(() => import('./blocks/testimonials/tabs')),
  'cta.default': dynamic(() => import('./blocks/cta/default')),
  'cta.cards-icons': dynamic(() => import('./blocks/cta/cards-icons')),
  'cta.email-signup': dynamic(() => import('./blocks/cta/email-signup')),
  'cta.finance-trading': dynamic(() => import('./blocks/cta/finance-trading')),
  'cta.heading-button': dynamic(() => import('./blocks/cta/heading-button')),
  'cta.image-button': dynamic(() => import('./blocks/cta/image-button')),
  'cta.mobile-app': dynamic(() => import('./blocks/cta/mobile-app')),
  'cta.qr-code': dynamic(() => import('./blocks/cta/qr-code')),
  'cta.tabs-mobile-app': dynamic(() => import('./blocks/cta/tabs-mobile-app')),
  'cta.two-cards': dynamic(() => import('./blocks/cta/two-cards')),
  'cta.banner-default': dynamic(() => import('./blocks/cta/banner-default')),
  'cta.banner-announcement': dynamic(() => import('./blocks/cta/banner-announcement')),
  'cta.banner-launch': dynamic(() => import('./blocks/cta/banner-launch')),
  'faq.accordion': dynamic(() => import('./blocks/faq/accordion')),
  'faq.default': dynamic(() => import('./blocks/faq/default')),
  'faq.grid-layout': dynamic(() => import('./blocks/faq/grid-layout')),
  'faq.help-center': dynamic(() => import('./blocks/faq/help-center')),
  'faq.help-center-search': dynamic(() => import('./blocks/faq/help-center-search')),
  'faq.customer-service': dynamic(() => import('./blocks/faq/customer-service')),
  'stats.default': dynamic(() => import('./blocks/stats/default')),
  'stats.card-statistics': dynamic(() => import('./blocks/stats/card-statistics')),
  'stats.carousel-slider': dynamic(() => import('./blocks/stats/carousel-slider')),
  'stats.heading-statistics': dynamic(() => import('./blocks/stats/heading-statistics')),
  'stats.icon-statistics': dynamic(() => import('./blocks/stats/icon-statistics')),
  'stats.illustration': dynamic(() => import('./blocks/stats/illustration')),
  'stats.content-social-proof': dynamic(() => import('./blocks/stats/content-social-proof')),
  'team.default': dynamic(() => import('./blocks/team/default')),
  'team.carousel-slider': dynamic(() => import('./blocks/team/carousel-slider')),
  'team.cta-grid': dynamic(() => import('./blocks/team/cta-grid')),
  'team.description': dynamic(() => import('./blocks/team/description')),
  'team.four-columns': dynamic(() => import('./blocks/team/four-columns')),
  'team.grid-cards': dynamic(() => import('./blocks/team/grid-cards')),
  'team.grid-clean': dynamic(() => import('./blocks/team/grid-clean')),
  'team.overlay-zoom': dynamic(() => import('./blocks/team/overlay-zoom')),
  'logo-cloud.default': dynamic(() => import('./blocks/logo-cloud/default')),
  'logo-cloud.4-columns': dynamic(() => import('./blocks/logo-cloud/4-columns')),
  'logo-cloud.cards-cta': dynamic(() => import('./blocks/logo-cloud/cards-cta')),
  'logo-cloud.cards-description': dynamic(() => import('./blocks/logo-cloud/cards-description')),
  'logo-cloud.heading-grid': dynamic(() => import('./blocks/logo-cloud/heading-grid')),
  'gallery.image-gallery': dynamic(() => import('./blocks/gallery/image-gallery')),
  'gallery.portfolio-default': dynamic(() => import('./blocks/gallery/portfolio-default')),
  'gallery.portfolio-alternate': dynamic(() => import('./blocks/gallery/portfolio-alternate')),
  'gallery.portfolio-carousel': dynamic(() => import('./blocks/gallery/portfolio-carousel')),
  'gallery.portfolio-featured-image': dynamic(() => import('./blocks/gallery/portfolio-featured-image')),
  'gallery.portfolio-grid-layout': dynamic(() => import('./blocks/gallery/portfolio-grid-layout')),
  'contact.default': dynamic(() => import('./blocks/contact/default')),
  'contact.address-location': dynamic(() => import('./blocks/contact/address-location')),
  'contact.background-image': dynamic(() => import('./blocks/contact/background-image')),
  'contact.company-information': dynamic(() => import('./blocks/contact/company-information')),
  'contact.help-center': dynamic(() => import('./blocks/contact/help-center')),
  'contact.links': dynamic(() => import('./blocks/contact/links')),
  'split-content.two-columns': dynamic(() => import('./blocks/split-content/two-columns')),
  'split-content.heading-description': dynamic(() => import('./blocks/split-content/heading-description')),
  'split-content.heading-images': dynamic(() => import('./blocks/split-content/heading-images')),
  'split-content.feature-list': dynamic(() => import('./blocks/split-content/feature-list')),
  'split-content.card-images': dynamic(() => import('./blocks/split-content/card-images')),
  'split-content.table-contents': dynamic(() => import('./blocks/split-content/table-contents')),
  'video-embed.content-video': dynamic(() => import('./blocks/video-embed/content-video')),
  'video-embed.hero-video-cta': dynamic(() => import('./blocks/video-embed/hero-video-cta')),
  'video-embed.hero-email-video': dynamic(() => import('./blocks/video-embed/hero-email-video')),
  'newsletter.default': dynamic(() => import('./blocks/newsletter/default')),
  'newsletter.banner': dynamic(() => import('./blocks/newsletter/banner')),
  'newsletter.email-signup-card': dynamic(() => import('./blocks/newsletter/email-signup-card')),
  'newsletter.modal-signup': dynamic(() => import('./blocks/newsletter/modal-signup')),
  'newsletter.popup-email': dynamic(() => import('./blocks/newsletter/popup-email')),
  'blog-list.default': dynamic(() => import('./blocks/blog-list/default')),
  'blog-list.card-with-image': dynamic(() => import('./blocks/blog-list/card-with-image')),
  'blog-list.centered-posts': dynamic(() => import('./blocks/blog-list/centered-posts')),
  'blog-list.featured-post': dynamic(() => import('./blocks/blog-list/featured-post')),
  'blog-list.list-with-heading': dynamic(() => import('./blocks/blog-list/list-with-heading')),
  'blog-list.publisher-related-default': dynamic(() => import('./blocks/blog-list/publisher-related-default')),
  'blog-list.publisher-related-grid': dynamic(() => import('./blocks/blog-list/publisher-related-grid')),
  'blog-list.publisher-related-carousel': dynamic(() => import('./blocks/blog-list/publisher-related-carousel')),
  'blog-list.publisher-related-horizontal': dynamic(() => import('./blocks/blog-list/publisher-related-horizontal')),
  'header.default': dynamic(() => import('./blocks/header/default')),
  'header.centered': dynamic(() => import('./blocks/header/centered')),
  'header.dropdown': dynamic(() => import('./blocks/header/dropdown')),
  'header.mega-dropdown': dynamic(() => import('./blocks/header/mega-dropdown')),
  'header.mega-menu': dynamic(() => import('./blocks/header/mega-menu')),
  'header.search': dynamic(() => import('./blocks/header/search')),
  'header.sub-navbar': dynamic(() => import('./blocks/header/sub-navbar')),
  'header.user-dropdown': dynamic(() => import('./blocks/header/user-dropdown')),
  'footer.default': dynamic(() => import('./blocks/footer/default')),
  'footer.flowbite-footer': dynamic(() => import('./blocks/footer/flowbite-footer')),
  'footer.newsletter': dynamic(() => import('./blocks/footer/newsletter')),
  'footer.pre-footer-cta': dynamic(() => import('./blocks/footer/pre-footer-cta')),
  'footer.sitemap-links': dynamic(() => import('./blocks/footer/sitemap-links')),
  'footer.sitemap-logo': dynamic(() => import('./blocks/footer/sitemap-logo')),
  'footer.social-media': dynamic(() => import('./blocks/footer/social-media')),
}

export const flowbiteTemplateIds = Object.keys(flowbiteRegistry)

export function resolveFlowbiteTemplate(templateId?: string): ComponentType<any> | undefined {
  if (!templateId) return undefined
  return flowbiteRegistry[templateId]
}
